{
 "title": "Team 4 Final",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Position of the robot",
   "type": "xychart",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "topic": "group-4/daniel/test/Rob2/ROBOTPOS/X"
    },
    {
     "topic": "group-4/daniel/test/Rob2/ROBOTPOS/Y"
    }
   ]
  },
  {
   "title": "Delta Robot 1 Positions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "topic": "group-4/daniel/test/Rob2/ROBOTPOS/X"
    },
    {
     "topic": "group-4/daniel/test/Rob2/ROBOTPOS/Y"
    },
    {
     "topic": "group-4/daniel/test/Rob2/ROBOTPOS/Z"
    }
   ]
  },
  {
   "title": "Parts Processed per hour",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    date_trunc('hour', server_timestamp) AS time,\r\n    COUNT(*) AS parts_count\r\nFROM public.iot_events\r\nWHERE sensor_id = 'ROBOTPOS.Z'\r\n  AND value < -99\r\n  AND $__timeFilter(server_timestamp)\r\nGROUP BY time\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Elapsed time (sec)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    server_timestamp AS time,\r\n        EXTRACT(EPOCH FROM (\r\n        server_timestamp - LAG(server_timestamp) OVER (ORDER BY server_timestamp)\r\n    )) AS time_diff_seconds\r\nFROM public.iot_events\r\nWHERE sensor_id = 'ROBOTPOS.Z'\r\n  AND value < -99\r\n AND $__timeFilter(server_timestamp)\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "All three motors with global limit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 1, "y": 22 },
   "targets": [
    {
     "rawSql": "WITH global_max AS (\r\n    SELECT\r\n        MAX(ABS(value)) AS max_abs_value\r\n    FROM public.iot_events\r\n    WHERE sensor_id IN ('MACTTORQUE[1]', 'MACTTORQUE[2]', 'MACTTORQUE[3]')\r\n      AND server_timestamp >= now() - interval '2 hours'\r\n)\r\nSELECT\r\n    e.server_timestamp AS time,\r\n    e.sensor_id,\r\n    ABS(e.value) AS abs_value,\r\n    --g.max_abs_value,\r\n    0.9 * g.max_abs_value AS threshold_80_percent\r\nFROM public.iot_events e\r\nCROSS JOIN global_max g\r\nWHERE e.sensor_id IN ('MACTTORQUE[1]', 'MACTTORQUE[2]', 'MACTTORQUE[3]')\r\n  AND e.$__timeFilter(server_timestamp)\r\n  AND ABS(e.value) > 0.8 * g.max_abs_value\r\nORDER BY time;\r\n"
    }
   ]
  }
 ]
}